const Exception = require('./Exception');
class UserAlreadyRegisteredException extends Exception {

}

module.exports = UserAlreadyRegisteredException